# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import card_pb2 as card__pb2


class CardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCards = channel.unary_unary(
                '/Card/getCards',
                request_serializer=card__pb2.Empty.SerializeToString,
                response_deserializer=card__pb2.IdCardsResponse.FromString,
                )
        self.getFullCard = channel.unary_unary(
                '/Card/getFullCard',
                request_serializer=card__pb2.SimpleCard.SerializeToString,
                response_deserializer=card__pb2.FullCard.FromString,
                )


class CardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCards(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFullCard(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCards': grpc.unary_unary_rpc_method_handler(
                    servicer.getCards,
                    request_deserializer=card__pb2.Empty.FromString,
                    response_serializer=card__pb2.IdCardsResponse.SerializeToString,
            ),
            'getFullCard': grpc.unary_unary_rpc_method_handler(
                    servicer.getFullCard,
                    request_deserializer=card__pb2.SimpleCard.FromString,
                    response_serializer=card__pb2.FullCard.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Card', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Card(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Card/getCards',
            card__pb2.Empty.SerializeToString,
            card__pb2.IdCardsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getFullCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Card/getFullCard',
            card__pb2.SimpleCard.SerializeToString,
            card__pb2.FullCard.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
