# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncard.proto\"\x07\n\x05\x45mpty\"\x18\n\nSimpleCard\x12\n\n\x02id\x18\x01 \x02(\x05\"U\n\x08\x46ullCard\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06health\x18\x03 \x02(\t\x12\x0e\n\x06\x61ttack\x18\x04 \x02(\t\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x05 \x02(\t\"!\n\x0fIdCardsResponse\x12\x0e\n\x06result\x18\x01 \x03(\x03\x32W\n\x04\x43\x61rd\x12&\n\x08getCards\x12\x06.Empty\x1a\x10.IdCardsResponse\"\x00\x12\'\n\x0bgetFullCard\x12\x0b.SimpleCard\x1a\t.FullCard\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_SIMPLECARD']._serialized_start=23
  _globals['_SIMPLECARD']._serialized_end=47
  _globals['_FULLCARD']._serialized_start=49
  _globals['_FULLCARD']._serialized_end=134
  _globals['_IDCARDSRESPONSE']._serialized_start=136
  _globals['_IDCARDSRESPONSE']._serialized_end=169
  _globals['_CARD']._serialized_start=171
  _globals['_CARD']._serialized_end=258
# @@protoc_insertion_point(module_scope)
