# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x02(\t\"8\n\x0cUserResponse\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x16\n\x06result\x18\x02 \x03(\x0b\x32\x06.Carda\"m\n\x0e\x41\x64\x64\x43\x61rdRequest\x12\x10\n\x08username\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x0e\n\x06health\x18\x04 \x02(\t\x12\x0e\n\x06\x61ttack\x18\x05 \x02(\t\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x06 \x02(\t\"G\n\x13RegisterCredentials\x12\x0c\n\x04mail\x18\x01 \x02(\t\x12\x10\n\x08username\x18\x02 \x02(\t\x12\x10\n\x08password\x18\x03 \x02(\t\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0f\n\x07message\x18\x02 \x02(\t\"R\n\x05\x43\x61rda\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06health\x18\x03 \x02(\t\x12\x0e\n\x06\x61ttack\x18\x04 \x02(\t\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x05 \x02(\t2\xb0\x01\n\x05users\x12-\n\x08Register\x12\x14.RegisterCredentials\x1a\t.Response\"\x00\x12\"\n\x05Login\x12\x0c.Credentials\x1a\t.Response\"\x00\x12\'\n\x07\x41\x64\x64\x43\x61rd\x12\x0f.AddCardRequest\x1a\t.Response\"\x00\x12+\n\x07GetUser\x12\x0f.GetUserRequest\x1a\r.UserResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREDENTIALS']._serialized_start=15
  _globals['_CREDENTIALS']._serialized_end=64
  _globals['_GETUSERREQUEST']._serialized_start=66
  _globals['_GETUSERREQUEST']._serialized_end=100
  _globals['_USERRESPONSE']._serialized_start=102
  _globals['_USERRESPONSE']._serialized_end=158
  _globals['_ADDCARDREQUEST']._serialized_start=160
  _globals['_ADDCARDREQUEST']._serialized_end=269
  _globals['_REGISTERCREDENTIALS']._serialized_start=271
  _globals['_REGISTERCREDENTIALS']._serialized_end=342
  _globals['_RESPONSE']._serialized_start=344
  _globals['_RESPONSE']._serialized_end=385
  _globals['_CARDA']._serialized_start=387
  _globals['_CARDA']._serialized_end=469
  _globals['_USERS']._serialized_start=472
  _globals['_USERS']._serialized_end=648
# @@protoc_insertion_point(module_scope)
